// <auto-generated />
namespace Api.Migrations

open System
open Data.Todo
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<Context>)>]
[<Migration("20230703043050_CreateTodosTable")>]
type CreateTodosTable() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "todos"
            ,columns = (fun table -> 
            {|
                id =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    ).Annotation("Sqlite:Autoincrement", true)
                title =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                description =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                state =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
            |})
            , constraints =
                (fun table -> 
                    table.PrimaryKey("PK_todos", (fun x -> (x.id) :> obj)
                    ) |> ignore
                )
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "todos"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder.HasAnnotation("ProductVersion", "6.0.19") |> ignore

        modelBuilder.Entity("Data.Todo+DB+TodoDB", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasColumnName("id") |> ignore

            b.Property<string>("Description")
                .IsRequired(true)
                .HasColumnType("TEXT")
                .HasColumnName("description") |> ignore

            b.Property<string>("State")
                .IsRequired(true)
                .HasColumnType("TEXT")
                .HasColumnName("state") |> ignore

            b.Property<string>("Title")
                .IsRequired(true)
                .HasColumnType("TEXT")
                .HasColumnName("title") |> ignore

            b.HasKey("Id")
                |> ignore


            b.ToTable("todos") |> ignore

        )) |> ignore

